import { usePluginStore, useWatchEvent } from '@/hooks/plugin.js';

type PSRecord = {
  script: string;
  label: string;
  busy: boolean;
};

export default function (name: string) {
  const ActionID = `${window.argv[3].plugin.uuid}.${name}`;

  const plugin = usePluginStore();
  const record: Record<string, PSRecord> = {};

  // Resolve the plugin's install root from the current document URL.
  // In production index.html lives at <pluginRoot>/index.html.
  // In dev mode it's served from _.html (same folder) — both work.
  const getPluginRoot = () => {
    const href = window.location.href;
    const lastSlash = href.lastIndexOf('/');
    return lastSlash === -1 ? href : href.slice(0, lastSlash);
  };

  // Build the launcher URL for a given script base name (no extension).
  // The launcher is a .vbs wrapper (auto-generated by script/autofile.cjs)
  // that runs powershell.exe with -WindowStyle Hidden so no console window
  // ever appears on screen.
  const getLauncherUrl = (script: string) => {
    const safe = script.replace(/[^a-zA-Z0-9._-]/g, '');
    return `${getPluginRoot()}/scripts/${safe}.vbs`;
  };

  // Render the canvas for the action key.
  const canvasFunc = (context: string, status: 'idle' | 'running' | 'done' | 'error' = 'idle') => {
    const action = plugin.getAction(context);
    if (!action) return;

    const canvas = document.createElement('canvas');
    canvas.width = 144;
    canvas.height = 144;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    // Background
    ctx.fillStyle = '#012456'; // PowerShell blue
    ctx.fillRect(0, 0, 144, 144);

    // PowerShell-style prompt
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 18px "Cascadia Mono", "Consolas", monospace';
    ctx.textAlign = 'left';
    ctx.textBaseline = 'top';
    ctx.fillText('PS>', 12, 12);

    // Script label (centered)
    const label = (record[context]?.label || record[context]?.script || 'no script').slice(0, 14);
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 18px "Segoe UI", sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(label, 72, 76);

    // Status badge
    let badge = '';
    let badgeColor = '#a0aec0';
    if (status === 'running') {
      badge = 'RUN';
      badgeColor = '#fbbf24';
    } else if (status === 'done') {
      badge = 'OK';
      badgeColor = '#22c55e';
    } else if (status === 'error') {
      badge = 'ERR';
      badgeColor = '#ef4444';
    } else {
      badge = 'READY';
      badgeColor = '#94a3b8';
    }
    ctx.fillStyle = badgeColor;
    ctx.font = 'bold 14px "Segoe UI", sans-serif';
    ctx.textBaseline = 'alphabetic';
    ctx.fillText(badge, 72, 130);

    action.setImage(canvas.toDataURL('image/png'));
  };

  const runScript = (context: string) => {
    const action = plugin.getAction(context);
    if (!action) return;

    const script = (record[context]?.script || '').trim();
    if (!script) {
      canvasFunc(context, 'error');
      return;
    }

    try {
      const url = getLauncherUrl(script);
      action.openUrl(url);
      record[context].busy = true;
      canvasFunc(context, 'running');

      // Reset to "done" shortly after — webview can't know real exit code.
      window.setTimeout(() => {
        if (!record[context]) return;
        record[context].busy = false;
        canvasFunc(context, 'done');
      }, 1200);
    } catch (err) {
      console.error('powershell launch error:', err);
      canvasFunc(context, 'error');
    }
  };

  const applySettings = (context: string, settings: any) => {
    const script = (settings?.script || 'SleepMonitor').toString();
    const label = (settings?.label || '').toString();
    record[context] = {
      script,
      label,
      busy: false
    };
  };

  useWatchEvent('action', {
    ActionID,
    willAppear({ context, payload }) {
      applySettings(context, payload?.settings);
      canvasFunc(context, 'idle');
    },
    willDisappear({ context }) {
      delete record[context];
    },
    didReceiveSettings({ context, payload }) {
      applySettings(context, payload?.settings);
      canvasFunc(context, 'idle');
    },
    keyUp({ context }) {
      runScript(context);
    },
    sendToPlugin({ context, payload }) {
      // Property Inspector "Test run" button.
      if (payload?.event === 'test-run') {
        runScript(context);
      }
    }
  });

  return {
    name,
    ActionID
  };
}
